version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: monthly
      time: "04:00"
    open-pull-requests-limit: 10
    groups:
      Microsoft:
        patterns:
          - "Microsoft.*"
          - "Serilog.*"
      ImageMagick:
        patterns:
          - "Magick.NET*"
      SystemIO:
        patterns:
          - "System.IO.Abstractions*"