trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Windows_x64:
      rid: 'win-x64'
    Windows_x86:
      rid: 'win-x86'
    Windows_arm:
      rid: 'win-arm'
    Windows_arm64:
      rid: 'win-arm64'
    Linux_x64:
      rid: 'linux-x64'
    Linux_musl_x64:
      rid: 'linux-musl-x64'
    Linux_arm:
      rid: 'linux-arm'
    Linux_osx:
      rid: 'osx-x64'

variables:
  buildConfiguration: 'Release'
  framework: 'net8.0'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

- script: dotnet publish OffUploader.Console -c $(buildConfiguration) -f $(framework) -r $(rid)
  displayName: 'dotnet publish OffUploader.Console $(buildConfiguration) $(rid)'

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: '$(framework)_$(rid)_$(buildConfiguration)'
    targetPath: 'OffUploader.Console/bin/$(buildConfiguration)/$(framework)/$(rid)/publish'
